### ISSUE TITLE
Pine<stuff> and LoRa and NDN (or equivalent)

### ISSUE THREAD

**Issue by dumblob** [lupyuen/wisblock-lora-receiver#1]
Hi, I noticed you're doing quite some work with LoRa while using (or even being affiliated with) Pine hardware/software.

A month ago I read that Pine will expand a lot into this LoRa domain. From what I know about LoRa, there is still no general standard used for global scale networking (incl. interconnection with existing fixed infrastructure - especially internet).

I'm not sure this is the best place to ask, but have you talked to Pine about deploying [NDN](https://github.com/named-data/NDN-packet-spec/issues/4 ) on all Pine devices to fill the hole and provide a standard interface to write applications?

**Comment by lupyuen** [comment]
Hi thanks for the suggestion :-) I'm new to NDN and I don't have much say in Pine64's product roadmap, but I'm checking to see what the community thinks...

https://twitter.com/MisterTechBlog/status/1371820486762532867?s=19

https://qoto.org/@lupyuen/105899787701200180

https://www.linkedin.com/posts/lupyuen_lora-activity-6777586550290153472-JhhA

The default standard network for LoRa would be LoRaWAN. Here are two popular LoRaWAN networks we could use:

1. The Things Network. Free network worldwide, with base stations operated by volunteers.

1. Helium Network. Commercial crypto network. More popular in the US.

More details:

https://lupyuen.github.io/articles/lora#lora-vs-lorawan

**Comment by lupyuen** [comment]
Hi again: I read the NDN Protocol Overview...

https://named-data.net/wp-content/uploads/2014/10/named_data_networking_ccr.pdf

It seems NDN is focused on high bandwidth content like Video Streaming and Real Time Conferencing?

This might not work well with LoRa because...

1.  LoRa operates on unlicensed ISM Frequency Bands. LoRa Packets may get dropped, and there's a rate limit (duty cycle).

1.  LoRa Packets can have a maximum of 256 bytes. So it's OK for sending short unreliable text messages, not for rich media.

Can you point me to the reference implementation of NDN over LoRa? I'm curious about the use case of NDN over a low-bandwidth, unreliable network like LoRa.

You can read about LoRaWAN and its constrained use of LoRa here...

https://twitter.com/MisterTechBlog/status/1370224529222500352?s=20

**Comment by dumblob** [comment]
Thanks for taking time to dig into this!

>It seems NDN is focused on high bandwidth content like Video Streaming and Real Time Conferencing?

From my understanding that's just demonstration because those are one of the biggest pain points of current internet.

But from my understanding NDN is fully generic. Am I right @yoursunny?

>Can you point me to the reference implementation of NDN over LoRa? I'm curious about the use case of NDN over a low-bandwidth, unreliable network like LoRa.

Well, NDN was designed to work also with IoT in mind if I'm not mistaken, so this shouldn't be a big concern. Or again, did I miss something truly fundamental @yoursunny?

**Comment by lupyuen** [comment]
Check out this comment...

https://twitter.com/IoTPanic/status/1371905197593796608?s=19

> Since LoRaWAN is used for MAC and transport, is NDN a actual replacement? Seems like you would still need some sort of MAC protocol, and not having a centralized architecture will cause bandwidth issues with LoRa.

**Comment by IoTPanic** [comment]
I spent time reading about NDN @dumblob and this is really cool, and exactly what I have been looking for, thank you for making the issue which caused @lupyuen to tweet about, which I saw. My main concern is the physical constraints of LoRa, it is designed to be usable in a high noise environment, the chirping (which you can see awesome videos of in @lupyuen's YT and twitter) takes a long period of time. Depending on the radio settings a LoRa transmission can take over a second, and has a limited packet length, so the total bandwidth is very limited. This is why gateways use a expensive 12-channel LoRa radio in order to 12x the potential bandwidth (This isn't actually the case, the channels each use different settings as a part of the frequency plan, one is in FSK mode, but for the sake of explanation) and therefore increase potential density. Its for "global" deployment, however using gateways, and currently there are blockchain based networks like Helium to decentralize over the internet. 

Reading up on NDN, my main concern is LoRa packet length. It could take 1+ seconds just for the signature and TPE encoding, which yeah, its not much info. A single pub/sub transaction using NDN would take too much time to be practical, and keep in mind LoRa devices are very low power, they are not usually awake long enough to route through each other or even listen for packets from each other. I agree with the video shown at this link that LoRaWAN gateways as nodes doesn't make sense https://dl.acm.org/doi/10.1145/3405656.3420228 but attempting a MAC with LoRa motes as nodes suggests fundamental misunderstanding of the typical LoRa device.

**Comment by dumblob** [comment]
@IoTPanic and @lupyuen thanks for explanation of the current state of the LoRa ecosystem. I was hoping LoRa already had some solution for "LoRa motes as nodes" (or similar). If it's not the case, then NDN indeed doesn't make that much sense as of now, unfortunately. At the same time this makes me more surprised that Pine has chosen to invest into LoRa if it actually can't reach the goals of "proper" decentralization.

Speaking about NDN, feel free to take a look at [PiCasso](https://www.fed4fire.eu/demo-stories/cc/picasso/#posters ) to get a whole picture. There are also alternatives to NDN - see e.g. [things to consider for IoT](https://trac.ietf.org/trac/irtf/wiki/icnrg#IoT ) (including e.g. LoRa I guess) and of course obligatory wikipedia list https://en.wikipedia.org/wiki/Information-centric_networking .

Generally I'm not the biggest fan of LoRaWAN, so I'll just point to one more resource if you're interested - it's a list of decentralized & ad-hoc & mesh networking technologies which might be handy for Pine or your own "stack": https://github.com/redecentralize/alternative-internet .

Feel free to close this issue any time if you find fit :wink:.

----

Now I have to wrap my head around Pine investing so much effort into something which doesn't seem to support mesh/ad-hoc/decentralized network well... :cry:

**Comment by dumblob** [comment]
Just found an alternative "MAC" with full mesh support (i.e. no gateways needed like in LoRaWAN): https://github.com/sudomesh/LoRaLayer2 (seems to be used also by the very successful **messaging application** [Meshtastic](https://www.meshtastic.org/ )).

**Comment by dumblob** [comment]
And some 2020 research for ICN (information centric networking - e.g. NDN) over LoRa (discussing why LoRaWAN MAC is impractical and providing a sketch of an alternative): https://www.researchgate.net/publication/344445287_Long-Range_IoT_Is_LoRaWAN_an_option_for_ICN .

**Comment by lupyuen** [comment]
Thanks for the interesting docs, will check them out!

**Comment by Pesa** [comment]
> And some 2020 research for ICN (information centric networking - e.g. NDN) over LoRa (discussing why LoRaWAN MAC is impractical and providing a sketch of an alternative): https://www.researchgate.net/publication/344445287_Long-Range_IoT_Is_LoRaWAN_an_option_for_ICN .

A (short) video presentation of that paper: https://youtu.be/1aw7smYzQiA

**Comment by dumblob** [comment]
One more list of closely related papers and research (with field-tested implementations!): https://i3.realmv6.org/publications/

**Comment by ogimenez-smtc** [comment]
Hi, I came here from Twitter :)

> From what I know about LoRa, there is still no general standard used for global scale networking (incl. interconnection with existing fixed infrastructure - especially internet).

There is some other projects related to IP, at least:
- [PyMesh](https://pycom.github.io/pydocs/firmwareapi/pycom/network/lora/pymesh.html) an IPv6 mesh network connected to the internet
- [Soon to be RFC9011](https://datatracker.ietf.org/doc/draft-ietf-lpwan-schc-over-lorawan/) an initiative backed my big companies to compress IPv6 headers and fragment packets over LoRaWAN. It is in RFC editors queue and should be an official RFC soon

Obviously you will not watch Youtube, but it can be useful from time to time :)
